In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler
import pickle

In [11]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [12]:
data=data.drop(["RowNumber","CustomerId","Surname"],axis=1)
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [13]:
label_encoder_gender=LabelEncoder()
data["Gender"]=label_encoder_gender.fit_transform(data["Gender"])
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [14]:
one_hot_encoder=OneHotEncoder()
geo_encoder=one_hot_encoder.fit_transform(data[["Geography"]]).toarray()
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [15]:
geo_encoded_df=pd.DataFrame(geo_encoder,columns=one_hot_encoder.get_feature_names_out(["Geography"]))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [16]:
data=pd.concat([data.drop("Geography",axis=1),geo_encoded_df],axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [17]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(one_hot_encoder,file)

In [18]:
X=data.drop("Exited",axis=1)
y=data["Exited"]

X

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 12 columns]

In [19]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
scalar=StandardScaler()
X_train=scalar.fit_transform(X_train)
X_test=scalar.transform(X_test)

In [21]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [22]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [23]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scalar,file)

### ANN IMPLEMENTATION

In [24]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

In [25]:
import datetime
from tensorflow.keras.layers import Dense

In [26]:
model=Sequential(
    [
        Dense(64,activation="relu",input_shape=(X_train.shape[1],)),
        Dense(32,activation="relu"),
        Dense(1,activation="sigmoid")
    ]
)

WARNING:tensorflow:From c:\Users\HP\Desktop\ANN project\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [28]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy
loss

keras.src.losses.BinaryCrossentropy

In [35]:
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [36]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
log_dir="logs/fit/"+ datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [37]:
early_stopping_callbacks=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [38]:
history=model.fit(
        X_train,y_train,validation_data=(X_test,y_test),epochs=100,
        callbacks=[tensorflow_callback,early_stopping_callbacks]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\HP\Desktop\ANN project\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\HP\Desktop\ANN project\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 2s 3ms/step - loss: 0.4069 - accuracy: 0.8289 - val_loss: 0.3670 - val_accuracy: 0.8565
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3538 - accuracy: 0.8549 - val_loss: 0.3438 - val_accuracy: 0.8570
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3471 - accuracy: 0.8580 - val_loss: 0.3451 - val_accuracy: 0.8560
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3433 - accuracy: 0.8605 - val_loss: 0.3400 - val_accuracy: 0.8635
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3406 - accuracy: 0.8612 - val_loss: 0.3408 - val_accuracy: 0.8585
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3390 - accuracy: 0.8602 - val_loss: 0.3407 - val_accuracy: 0.8595
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3388 - accuracy: 0.8618 - val_loss: 0.3472 - val_accuracy: 0.8570
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3319 - accuracy: 0.8644 - val_loss: 0.3438 - val_accuracy: 0.8635
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3298 - accuracy: 0.8634 - val_loss: 0.3505 - val_accuracy: 0.8580
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3271 - accuracy: 0.8660 - val_loss: 0.3499 - val_accuracy: 0.8540
Epoch 11/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3282 - accuracy: 0.8656 - val_loss: 0.3464 - val_accuracy: 0.8550
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3244 - accuracy: 0.8655 - val_loss: 0.3470 - val_accuracy: 0.8580
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3215 - accuracy: 0.8652 - val_loss: 0.3590 - val_accuracy: 0.8595
Epoch 14/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3216 - accuracy: 0.8683 - val_loss: 0.3600 - val_accuracy: 0.8605

In [39]:
model.save('model.h5')

c:\Users\HP\Desktop\ANN project\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [40]:
%load_ext tensorboard

In [41]:
%tensorboard --logdir logs/fit